name: RAPGOAT Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  RAPGOAT-Action:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install the latest Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RAPGOAT Actions
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          python RAPGOAT/main.py

      - name: Commit and push changes
        run: |
          git config user.name "ImanMontajabi"
          git config user.email "iman.montajabi@gmail.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "🛢️️ Database updated ⏰ ${timestamp}" || exit 0
          git push origin main
