name: RAPGOAT Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  RAPGOAT-Action:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RAPGOAT Actions
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: |
          python RAPGOAT/main.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "ImanMontajabi"
          git config user.email "iman.montajabi@gmail.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Database updated at ${timestamp}" || exit 0
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/ImanMontajabi/RAPGOAT
          git push origin main

