name: RAPGOAT Actions

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 11 * * *"

env:
  client_id: ${{ secrets.CLIENT_ID }}
  client_secret: ${{ secrets.CLIENT_SECRET }}

jobs:
  RAPGOAT-Action:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start RAPGOAT
        run: |
          python RAPGOAT/main.py

      - name: Commit and push changes
        run: |
          git config user.name "Iman Montajabi"
          git config user.email "iman.montajabi@gmail.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "🪁️ Database updated ⏰ ${timestamp}" || exit 0
          git push origin main
